### PR TITLE
[FLINK-32353] [hotfix] build against last flink 1.16 and 1.17 and enable archunit only on main flink release

### PR DESCRIPTION
**Pull request by echauchot**
The mini cluster rule has been fixed in [flink-1.18](https://github.com/apache/flink/pull/22399/)

- CassandraConnectorITCase does not use/needs MiniCluster so it is still an "violation" but the rule message has changed.
- the "violation" for CassandraSourceITCase is now gone as the rule was fixed.

### CODE REVIEW

**Comment by echauchot** [comment]
Maybe we should add tests against flink master snaphot ? Right now there is only 1.16.x 1.17.x

**Comment by echauchot** [comment]
> Maybe we should add tests against flink master snapshot ? Right now there is only 1.16.x 1.17.x in PRs

added 1.18-SNAPSHOT tests

**Comment by echauchot** [comment]
> > Maybe we should add tests against flink master snapshot ? Right now there is only 1.16.x 1.17.x in PRs
> 
> added 1.18-SNAPSHOT tests

Got it, the failure we observe is due to flink 1.16/1.17 updating achunit freeze store with different rules. Then, the flink-1.18 build fails because it has the new rules so the violations are different.

I believe, having the build on master in PRs makes sense because it allows to not wait for weekly tests to see regressions.
@MartijnVisser how should we setup the build to avoid the behavior described above ?

**Comment by echauchot** [comment]
> > > Maybe we should add tests against flink master snapshot ? Right now there is only 1.16.x 1.17.x in PRs
> > 
> > 
> > added 1.18-SNAPSHOT tests
> 
> Got it, the failure we observe is due to flink 1.16/1.17 updating achunit freeze store with different rules. Then, the [flink-1](https://issues.apache.org/jira/browse/FLINK-1).18 build fails because it has the new rules so the violations are different.
> 
> I believe, having the build against flink master in PRs makes sense because it allows to not wait for weekly tests to see regressions. @MartijnVisser how should we setup the build to avoid the behavior described above ?

What about adding Flink version to archunit violations store name ?

**Comment by echauchot** [comment]
It is an hotfix, so, self-merging

**Comment by tzulitai** [comment]
Hey @echauchot I'm trying to fix the same thing for the Kafka connector, but I could use your help on understanding the change here.

What exactly is the change that enables archunit only for main Flink releases? I can't seem to link what was changed in this PR that would have that effect.

**Comment by echauchot** [comment]
Hi @tzulitai yes I fell back this PR's scope to just upgrading the versions hence the self merge. But, as I just wrote in [this ticket](https://issues.apache.org/jira/browse/FLINK-33104?focusedCommentId=17772516&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17772516), I'll submit a new PR to change the build system and tackle this problem.

**Pull request merged**
