### PR TITLE
[FLINK-31749] Disable cassandra driver metrics as they are not integrated with Flink metrics

### PR DESCRIPTION
**Pull request by echauchot**
R: @RyanSkraba 
CC: @zentol @dannycranmer

### CODE REVIEW

**Review by dannycranmer — APPROVED** [review]
LGTM

**Review by leonardBang — APPROVED** [review]
LGTM, But please note that The  issue should be [FLINK-31927](https://issues.apache.org/jira/browse/FLINK-31927) instead of [FLINK-31749](https://issues.apache.org/jira/browse/FLINK-31749) .

@zentol @dannycranmer Would you like to merge this PR and prepare a new release candidate ?

**Comment by echauchot** [comment]
> LGTM, But please note that The issue should be [FLINK-31927](https://issues.apache.org/jira/browse/FLINK-31927) instead of [FLINK-31749](https://issues.apache.org/jira/browse/FLINK-31749) .
> 

oops I saw your message with the wrong ticket number after hitting merge so the commit message shows the wrong ticket but I changed the PR name at least. We will obviously not rebase master to change the commit message. 

> @zentol @dannycranmer Would you like to merge this PR and prepare a new release candidate ?

**Comment by leonardBang** [comment]
> @leonardBang with 3 approvals I'll self merge

Yeah, you should have the access, but the commit message you forget to update the issue, please keep in mind in next time.

**Comment by echauchot** [comment]
> > @leonardBang with 3 approvals I'll self merge
> 
> Yeah, you should have the access, but the commit message you forget to update the issue, please keep in mind in next time.

yes, as I wrote above, I was too quick in merging this PR. Sorry about that. Thanks for pointing out the wrong ticket number.

**Comment by echauchot** [comment]
> > yes, as I wrote above, I was too quick in merging this PR. Sorry about that. Thanks for pointing out the wrong ticket number.
> 
> Take it easy, everyone might miss some details, have a good day!

Yes, no problem. Have a good day too !

**Comment by dannycranmer** [comment]
I realised we had not merged into the v3.1 branch. I am working on the 3.1.0-RC2 and when cherry picking to v3.1 I will at least fix the JIRA ID there.

**Comment by echauchot** [comment]
> I realised we had not merged into the v3.1 branch. I am working on the 3.1.0-RC2 and when cherry picking to v3.1 I will at least fix the JIRA ID there.

@dannycranmer you do the cherry pick ?

**Pull request merged**
