### PR TITLE
[FLINK-32222] avoid using non-public DataInputDeserializer and DataOutputSerializer

### PR DESCRIPTION
**Pull request by echauchot**
Linked to [this PR](https://github.com/apache/flink/pull/22667): 

- Removed non public classes usages except Preconditions, VisibleForTesting and ClosureCleaner for which violations are added here. I updated violations store in advance of the merge of the above PR that fixes the Connector rule.

- Removed overkill ThreadLocal cache as the other similar connectors, don't cache Streams for Split serialization. This allows simpler and more standard serialization code.

@zentol PTAL ?

### CODE REVIEW

**Review by zentol — APPROVED** [review]
This doesn't seem like such a bad replacement for the data*serializers. +1

This would also work, and _may_ look nicer? :shrug: 

```
        final ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();                
        try (final ObjectOutputStream objectOutputStream =
                        new ObjectOutputStream(byteArrayOutputStream)) {
            BigIntegerSerializationUtils.write(
                    cassandraSplit.getRingRangeStart(), objectOutputStream);
            BigIntegerSerializationUtils.write(
                    cassandraSplit.getRingRangeEnd(), objectOutputStream);
        }
        return byteArrayOutputStream.toByteArray();
```

**Comment by echauchot** [comment]
> This doesn't seem like such a bad replacement for the data*serializers. +1
> 
> This would also work, and _may_ look nicer? shrug
> 
> ```
>         final ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();                
>         try (final ObjectOutputStream objectOutputStream =
>                         new ObjectOutputStream(byteArrayOutputStream)) {
>             BigIntegerSerializationUtils.write(
>                     cassandraSplit.getRingRangeStart(), objectOutputStream);
>             BigIntegerSerializationUtils.write(
>                     cassandraSplit.getRingRangeEnd(), objectOutputStream);
>         }
>         return byteArrayOutputStream.toByteArray();
> ```

But that is the same code I pushed except you've put the ByteArrayOutputStream creation outside of the try-with-resources
and the return outside of the try block ?

This is more of a coding style matter. The other connectors I've looked at (kafka and pulsar) and the other serializer in cassandra connector all use the coding style I used, so for consistency I would tend to keep it.

**Comment by zentol** [comment]
> But that is the same code I pushed except 

Main thing is avoiding the explicit flush call :shrug:

**Comment by echauchot** [comment]
> > But that is the same code I pushed except
> 
> Main thing is avoiding the explicit flush call shrug

Ah, I missed it ! Yeah, better, having the try-with-resources closing before the return statement allows automatically calling ObjectOutputStream#close() that does the flush. 
Thanks for the suggestion, I'll update the other Cassandra serializer as well.

**Comment by echauchot** [comment]
> > > But that is the same code I pushed except
> > 
> > 
> > Main thing is avoiding the explicit flush call shrug
> 
> Ah, I missed it ! Yeah, better, having the try-with-resources closing before the return statement allows automatically calling ObjectOutputStream#close() that does the flush. Thanks for the suggestion, I'll update the other Cassandra serializer as well.

Done, merging as soon as I have the tests passing

**Pull request merged**
